name: Specification Validation

on:
  pull_request:
    paths:
      - "docs/specs/**"
      - "src/**"

jobs:
  validate-specs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Check Spec Links
        run: |
          # Validate that spec files are properly linked
          # Check for broken internal references
          echo "Validating specification documents..."

      - name: Lint Markdown
        uses: articulate/actions-markdownlint@v1
        with:
          config: .markdownlint.json
          files: "docs/**/*.md"
